version: '3.8'

services:
  trustworthy-rag:
    build:
      context: .
      dockerfile: trustworthy-RAG/Dockerfile
    ports:
      - "8502:8502"
    env_file:
      - trustworthy-RAG/.env
    volumes:
      - ./trustworthy-RAG:/app

  github-chat:
    build:
      context: .
      dockerfile: github-chat/Dockerfile
    ports:
      - "8501:8501"
    env_file:
      - github-chat/.env
    volumes:
      - ./github-chat:/app 